Update create prototype customizations
AmpersandTarski/RAP pull request #255
Opened 2023-03-10 13:49 UTC by FreekOrdina

Most important:
- changes in ExecEngineFunctions.php
- Added manifest template file in folder ./RAP4/templates
- Added two environmental paramters: DEPLOYMENT and KUBERNETES_NAMESPACE, which are now included in the RAP configmap

2023-03-18 19:07 UTC, Michiel-s commented on RAP4/Dockerfile
> +  && apt-get install -y docker-ce-cli
Running apt-get update again is not needed. Remove to safe time

2023-03-18 19:07 UTC, Michiel-s commented on RAP4/Dockerfile
> +RUN apt-get update && \
Same. Apt-get update again is not needed.

2023-03-18 19:13 UTC, Michiel-s commented on RAP4/customizations/bootstrap/files/ExecEngineFunctions.php
> +    $deployment = getenv('DEPLOYMENT');
Suggestion to rename env to `RAP_DEPLOYMENT` to make explicit that this variable is for the RAP application. 

That is also more consistent with the other RAP env variables: `RAP_HOST_NAME`, `RAP_STUDENT_PROTO_IMAGE`, etc.

2023-03-18 19:13 UTC, Michiel-s commented on RAP4/customizations/bootstrap/files/ExecEngineFunctions.php
> +        $namespace=getenv('KUBERNETES_NAMESPACE');
Prefix env with `RAP_`

2023-03-18 19:18 UTC, Michiel-s commented on RAP4/customizations/bootstrap/files/ExecEngineFunctions.php
> +        $manifestFile = $ee->getApp()->getSettings()->get('global.absolutePath') . '/templates/student-manifest-template.yaml';
The `templates` folder is used for the frontend templates files. Unrelated to the deployment template. I suggest to move this `student-manifest-template.yaml` to the same folder as the ExecEngineFunctions.php that uses it or in backend folder `RAP4/customizations/extensions/RAP4/src`.

2023-03-18 19:20 UTC, Michiel-s commented on RAP4/customizations/bootstrap/files/ExecEngineFunctions.php
> +        $manifest=file_get_contents($manifestFile);
file_get_contents() may return false when an error occurs, e.g. when the specified file does not exists. Add a `!== false` check and throw exception in case of false.

2023-03-18 19:24 UTC, Michiel-s commented on RAP4/customizations/bootstrap/files/ExecEngineFunctions.php
> +        $command = new Command("kubectl apply -f {$studentManifestFile}", null, $ee->getLogger());
Use `kubectl apply` as first argument of new Command constructor method.
Add `-f {$studentManifestFile}` in second argument in array. See example in `docker rm` command below.

2023-03-18 19:29 UTC, Michiel-s commented on RAP4/templates/student-manifest-template.yaml
> +          image: sheriffbalunywa/rap4-student-proto:2.1
Needs to be adapted to ampersandtarski/rap4-student-prototype.

Requires v2.1 of RAP4 student image to be build and pushed to docker hub.

2023-03-18 19:32 UTC, Michiel-s commented on RAP4/templates/student-manifest-template.yaml
> +            - configMapRef:
Replace configmap by stating the environments variables in the container spec directly.

You can use the `env` for this instead of `envFrom`.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#container-v1-core

2023-03-18 19:32 UTC, Michiel-s commented on RAP4/templates/student-manifest-template.yaml
> +# configmap used by student
Configmap not needed. Can be replaced by specifying env directly in the container spec. See comment below

2023-03-18 19:38 UTC, Michiel-s commented on deployment/resources/acr-credentials.yaml
> +  .dockerconfigjson: eyJhdXRocyI6eyJhbXBlcnNhbmRyYXAuYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6ImFtcGVyc2FuZHJhcCIsInBhc3N3b3JkIjoidDkzL3poajBjOUtpdS9laDVMelAwbC9PYXZMcGpabTFvTHhOV3BYVk1oK0FDUkJmekJSTSIsImF1dG
This encoded data contains password and auth token. Please renew and find another solution that doesn't require to check-in this to git repo.

2023-03-18 19:41 UTC, Michiel-s requested changes
Please resolve review comments

2023-03-22 09:55 UTC, FreekOrdina commented on RAP4/customizations/bootstrap/files/ExecEngineFunctions.php
> +        $manifestFile = $ee->getApp()->getSettings()->get('global.absolutePath') . '/templates/student-manifest-template.yaml';
Moved file to the same folder as ExecEngineFunctions.php

2023-03-22 10:13 UTC, FreekOrdina commented on RAP4/Dockerfile
> +  && apt-get install -y docker-ce-cli
This apt-get update is required because of the line above:
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

It cannot find the package. Moving it before the first apt-get update doesn't work.

2023-03-24 08:23 UTC, FreekOrdina commented on RAP4/templates/student-manifest-template.yaml
> +            - configMapRef:
Would you advice not to use configmaps at all? For RAP and enroll I also save environmental variables in config files.

2023-03-24 08:26 UTC, FreekOrdina commented on deployment/resources/acr-credentials.yaml
> +  .dockerconfigjson: eyJhdXRocyI6eyJhbXBlcnNhbmRyYXAuYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6ImFtcGVyc2FuZHJhcCIsInBhc3N3b3JkIjoidDkzL3poajBjOUtpdS9laDVMelAwbC9PYXZMcGpabTFvTHhOV3BYVk1oK0FDUkJmekJSTSIsImF1dG
This could be resolved by pushing the secret file directly to the Kubernetes Cluster, then it won't be saved in the public Git repo. However, I'll remove this file from the repo anyway, because we won't be using the private ACR repo, but public Docker Hub.

We'll need to push the Dockerfile to Docker hub though, for which I don't have permission.

2023-03-24 08:27 UTC, FreekOrdina commented on RAP4/templates/student-manifest-template.yaml
> +          image: sheriffbalunywa/rap4-student-proto:2.1
We'll need to push the Dockerfile to Docker hub, for which I don't have permission.

2023-04-01 12:25 UTC, Michiel-s commented on RAP4/templates/student-manifest-template.yaml
> +            - configMapRef:
Indeed. In this case it doesn't provide additional value.

2023-04-01 12:27 UTC, Michiel-s approved these changes

2023-04-01 16:39 UTC, merged